#Exercice01
Écrivez un programme qui trouvera tous ces nombres qui sont divisibles par 7 mais ne sont pas un multiple de 5, entre 2000 et 3200 (tous deux inclus). Les nombres obtenus doivent être imprimés dans une liste.

Conseils: envisagez d'utiliser la méthode range (#begin, #end) 

In [ ]:
MyList = []
for i in range(2000,3200):
  if i%7 == 0 and i%5 != 0:
    MyList.append(i)

print(MyList)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


#Exercice02
 Écrivez un programme qui peut calculer la factorielle d'un nombre donné. (la factorielle de n est le produit de tous les nombres entiers positifs inférieurs ou égaux à n). par exemple factoriel (5) = 5 x 4 x 3 x 2 x 1 le résultat est 120. (ie factoriel (0) = 1)

In [ ]:
nbr = 5
fact = 1
for i in range(1, nbr+1):
  fact = fact * i 
print(nbr,'! = ',fact)

5 ! =  120


#Exercice03
Avec un nombre entier donné n, écrivez un programme pour générer un dictionnaire contenant (i, i * i) tel qu'un nombre entier compris entre 1 et n (tous deux inclus). puis le programme doit imprimer le dictionnaire. Supposons que l'entrée suivante soit fournie au programme: 8 Ensuite, la sortie doit être: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64 }  

In [ ]:
for i in range(1, 9):
  MyDict[i]=i*i
MyDict

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

#Exercice04
Étant donné une chaîne non vide et un int n, retourne une nouvelle chaîne où le caractère à l'index n a été supprimé. La valeur de n sera un index valide d'un caractère dans la chaîne d'origine (c'est-à-dire que n sera dans la plage 0..len (str) -1 inclus). 

missing_char ('kitten', 1) → 'ktten' par exemple ici on supprime "i" qui se trouve dans l'index 1

missing_char ('chaton', 0) → 'itten' ici on supprime "k" qui est dans l'index 0

missing_char ('chaton', 4) → 'kittn' ici on supprime "e" qui est dans l'index 4

In [ ]:
def missing_char(x,y) :
    s=x.replace(x[y],"")
    print (s)

x = 'kitten'
y = int(input("indiquer l'index de lettre a supprimer : "))

if y < len(x):
  missing_char(x,y)
else:
  print("l'index indiquer est plus grand que la chaine")

indiquer l'index de lettre a supprimer : 4
kittn


#Exercice05
Ecrivez un programme NumPy pour convertir un tableau NumPy en une structure de liste Python.

Production attendue: 

Éléments du tableau d'origine: [[0 1] [2 3] [4 5]] 

Tableau à répertorier: [[0, 1], [2, 3], [4, 5]] 
 

Astuce: nous pouvons utiliser la fonction to_list () pour assurer la conversion

In [ ]:
import numpy as np
arr = np.array([[0, 1], [2, 3], [4, 5]])
print(arr)

def to_list():
  MyList = arr.tolist()
  return(MyList)
  
to_list()

[[0 1]
 [2 3]
 [4 5]]


[[0, 1], [2, 3], [4, 5]]

#Exercice06
Ecrivez un programme NumPy pour calculer la matrice de covariance de deux tableaux donnés. 

Tableau original1: [0 1 2] 

Tableau original2: [2 1 0] 

Matrice de covariance desdits tableaux: [[1. -1.] [-1. 1.]]
 

Astuce: nous pouvons utiliser la fonction np.cov () pour calculer la covariance entre ces deux tableaux

In [ ]:
import numpy as np
arr1 = np.array([0, 1, 2])
arr2 = np.array([2, 1, 0])

def conv(x,y):
  mat = np.cov(x,y)
  print(mat)

conv(arr1,arr2)

[[ 1. -1.]
 [-1.  1.]]


In [ ]:
import numpy as np
arr1 = np.array([0, 1, 2])
arr2 = np.array([2, 1, 0])
mat = np.cov(arr1,arr2)
print(mat)

[[ 1. -1.]
 [-1.  1.]]


#Exercice07
Question: Écrivez un programme qui calcule et imprime la valeur selon la formule donnée: Q = Racine carrée de [(2 * C * D) / H] 

Voici les valeurs fixes de C et H: C est 50. H est 30. 

D est la variable dont les valeurs doivent être entrées dans votre programme dans une séquence séparée par des virgules. (cela signifie que D contient plus que la valeur)

Exemple Supposons que la séquence d'entrée séparée par des virgules soit donnée au programme: 100,150,180 La sortie du programme doit être: 18,22,24 

Pour mieux comprendre, nous obtiendrons un résultat pour chaque valeur de D: Q1 = Racine carrée de [(2 * C * 100) / H] = 18, Q2 = Racine carrée de [(2 * C * 150) / H] = 22 et Q3 = Racine carrée de [(2 * C * 180) / H] = 24

Conseils: si la sortie reçue est sous forme décimale, elle doit être arrondie à sa valeur la plus proche (par exemple, si la sortie reçue est 26,0, elle doit être imprimée comme 26). doit être supposé être une entrée de console. 

In [ ]:
import math
C = int(50)
H = int(30)
D = 100,150,180
i = 1
for x in D:
  print('D', i, ' = ', x)
  Y = int((2*C*x/H))
  Q = round(math.sqrt(Y))
  print('Q = ',Q)
  i += 1

D 1  =  100
Q =  18
D 2  =  150
Q =  22
D 3  =  180
Q =  24
